In [17]:
from sklearn import linear_model
import tensorflow as tf

path = '/Users/jiaxingchen/CoursesWorkshops/PSU/2020Spring/deep_learning/homework1/mnist.npz'
(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.mnist.load_data(path)
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

LR = linear_model.LinearRegression()
model = LR.fit(train_images, train_labels)
print(model.score(train_images, train_labels))
#print(model.coef_)
#print(model.intercept_)

print(model.predict(test_images))
print(model.score(test_images, test_labels))



0.6161200946544948
[6.3242173 2.3119516 1.6173074 ... 7.9008226 5.5023675 5.7617655]
0.6242359914970583


In [18]:
import tensorflow as tf
from sklearn import tree

path = '/Users/jiaxingchen/CoursesWorkshops/PSU/2020Spring/deep_learning/homework1/mnist.npz'
(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.mnist.load_data(path)
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

DT = tree.DecisionTreeClassifier()
model = DT.fit(train_images, train_labels)

print(model.predict(test_images))
print(model.score(test_images, test_labels))



[7 2 1 ... 4 5 6]
0.8771


In [28]:
import tensorflow as tf
from sklearn.svm import SVC

path = '/Users/jiaxingchen/CoursesWorkshops/PSU/2020Spring/deep_learning/homework1/mnist.npz'
(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.mnist.load_data(path)
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

model = SVC(kernel='rbf')
model.fit(train_images, train_labels)

print(model.predict(test_images))
print(model.score(test_images, test_labels))



[7 2 1 ... 4 5 6]
0.9792
